name: ut-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - llama-index
      - llama-index-readers-file
      - llama-index-embeddings-huggingface
      - llama_index-vector-stores-pinecone
      - llama-index-llms-openai
      - llama-index-core
      - openai
      - langchain
      - scrapy
      - streamlit
